apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"8"},"creationTimestamp":"2024-11-06T17:36:46Z","generation":9,"name":"sprgboot-app","namespace":"noelapp","resourceVersion":"381472748","uid":"c6ca2d7b-24f4-4152-8d25-34e6fc8bf5eb"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"sprgboot-app"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"sprgboot-app"}},"spec":{"containers":[{"image":"noel135/img-repo:nodejs","imagePullPolicy":"Always","name":"sprgboot-app","ports":[{"containerPort":3001,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2024-11-09T09:09:31Z","lastUpdateTime":"2024-11-09T09:09:31Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2024-11-09T09:07:59Z","lastUpdateTime":"2024-11-11T07:45:25Z","message":"ReplicaSet \"sample-app-64ff9487c7\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":9,"readyReplicas":2,"replicas":2,"updatedReplicas":2}}
  creationTimestamp: "2024-11-12T07:22:32Z"
  generation: 1
  name: sprgboot-app
  namespace: noelspg
  resourceVersion: "382483811"
  uid: 0d5c024f-da26-4204-a6c8-77a0ac37b370
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sprgboot-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sprgboot-app
    spec:
      containers:
      - image: noel135/img-repo:22
        imagePullPolicy: Always
        name: sprgboot-app
        ports:
        - containerPort: 8090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-11-12T07:22:36Z"
    lastUpdateTime: "2024-11-12T07:22:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-11-12T07:22:32Z"
    lastUpdateTime: "2024-11-12T07:22:36Z"
    message: ReplicaSet "sprgboot-app-788966476d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
